### ISSUE TITLE
Players not shown

### ISSUE THREAD

**Issue by asdat3** [Whitebrim/HuntDMA#1]
Hey, somehow with https://github.com/Whitebrim/HuntDMA/commit/14212fe72cf072b22c8c90da7a8d87606f165564 and manual updating of the offsets it works fine (I just changed aimbot, kmbox, env) as you introduced more and more useful stuff however I just forked the current version adjusted the aimbot and built it, it shows everything but players on the esp for some reason. I havent changed anything that should have affected that at all.

You can check for yourself in the commits:
https://github.com/asdat3/HuntDMA

I am pretty certain the current version (of this repo) has some sort of bug that doesnt show players but I might be stupid

**Comment by asdat3** [comment]
okay musst be an issue on my end, thanks for sharing

**Comment by Whitebrim** [comment]
> Hey, somehow with [14212fe](https://github.com/Whitebrim/HuntDMA/commit/14212fe72cf072b22c8c90da7a8d87606f165564) and manual updating of the offsets it works fine (I just changed aimbot, kmbox, env) as you introduced more and more useful stuff however I just forked the current version adjusted the aimbot and built it, it shows everything but players on the esp for some reason. I havent changed anything that should have affected that at all.
> 
> You can check for yourself in the commits: https://github.com/asdat3/HuntDMA
> 
> I am pretty certain the current version (of this repo) has some sort of bug that doesnt show players but I might be stupid

Players were not showing because hp chain was broken

**Comment by asdat3** [comment]
makes sense, I managed to get it running with aimbot, however your indicator for the head would be awesome if it could be adjusted if the player is crouching. 

btw: as you added uncomment this for aim in the init.cpp - a few lines below is the aimbot loop which is also commented out might wanna add that above idk. thanks for sharing

**Comment by Whitebrim** [comment]
> btw: as you added uncomment this for aim in the init.cpp - a few lines below is the aimbot loop which is also commented out might wanna add that above idk. thanks for sharing

I made better: const bool in Init.h `enableAimBot = false;`
And checks for this bool everywhere where I disabled aimbot. It it's false, then aimbot code will not be compiled.

**Comment by asdat3** [comment]
great thanks, if you want you could also update the aim target selection, it currently still aims at dead or extracted players

**Comment by Whitebrim** [comment]
> great thanks, if you want you could also update the aim target selection, it currently still aims at dead or extracted players

You can check for dead yourself. There's code in PlaterESP.cpp that check hp for valid number. If it's not in range 1-150 then player is dead.

I don't know how to know if player has extracted.

**Comment by asdat3** [comment]
already did but I didnt do anything clean enough to make a commit, maybe when I find some free time I will implement my aim fix and make a contribute, thanks for all your work, really amazing
