### ISSUE TITLE
How do I configure Kmbox?

### ISSUE THREAD

**Issue by Bair404** [Whitebrim/HuntDMA#4]
I am using Kmbox Net. I'm not sure what configurations should be placed in which folders. Should I edit the source code, or configure it in the generated configuration file after building the executable program?

**Comment by Whitebrim** [comment]
> I am using Kmbox Net. I'm not sure what configurations should be placed in which folders. Should I edit the source code, or configure it in the generated configuration file after building the executable program?

You should compile with https://github.com/Whitebrim/HuntDMA/blob/main/HuntDMA%2FGraphics%2FStart%20Up%2FInit.h#L6
changed to true. 

I didn't change aimbot functionality and didn't test it. It's in the same state as in [Intel's repo](https://github.com/IntelSDM/HuntDMA).
